name: Vivaldi
flatpak: com.vivaldi.Vivaldi
system_bin: vivaldi
can_isolate: true
can_start_maximized: true
desktop_file_name_prefix: com.vivaldi.Vivaldi.vivaldi
base: chromium
issues:
  en:
    - Does not remember window size and position
